# Generated by Django 4.1.4 on 2023-01-07 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_guide_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsestatus',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='guide.guide'),
        ),
    ]
