# Generated by Django 4.1.4 on 2023-01-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_alter_responsestatus_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsestatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='responsestatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
