# Generated by Django 3.2.16 on 2023-01-29 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
        ('guide', '0004_responsestatus_created_at_responsestatus_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='destination.location'),
        ),
    ]
