# Generated by Django 3.2.16 on 2023-02-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_auto_20230205_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
