# Generated by Django 4.1.4 on 2022-12-07 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destination', '0001_initial'),
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.destination')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.guide')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tourname')),
            ],
        ),
    ]
