# Generated by Django 4.1.4 on 2023-01-04 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
        ('tour', '0002_alter_tour_destination_alter_tour_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='guide.guide'),
        ),
    ]
