# Generated by Django 4.1.4 on 2023-01-04 17:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_alter_tour_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='supplementary_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
    ]
