# Generated by Django 3.2.16 on 2023-01-16 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_tour_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.tourname'),
        ),
    ]
