# Generated by Django 3.2.16 on 2023-02-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_alter_tour_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_time',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], default='', max_length=2),
        ),
    ]
