# Generated by Django 3.2.16 on 2023-02-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_tour_tour_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
