# Generated by Django 3.2.16 on 2023-02-18 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_tourlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.tourlocation'),
        ),
    ]
