# Generated by Django 3.2.16 on 2023-02-20 18:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_tour_tour_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourlocation',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
    ]
