# Generated by Django 3.2.16 on 2023-02-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_auto_20230215_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='file_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
