# Generated by Django 3.2.16 on 2023-02-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_tour_tour_location'),
        ('destination', '0004_destination_tour_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='tour_locations',
        ),
        migrations.AddField(
            model_name='location',
            name='tour_locations',
            field=models.ManyToManyField(blank=True, related_name='destinations', to='tour.TourLocation'),
        ),
    ]
